"""
The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""

import math


def is_perfect_square(n):
    x = math.ceil((math.sqrt(n)))
    if x**2 == n:
        return True
    else:
        return False


def max_num(m):
    x = 3
    n = 2
    while n <= m:
        n = 2
        number = sum([c for c in range(1, x+1)])
        for i in range(2, math.ceil(math.sqrt(number))):
            if number % i == 0:
                n += 2
        if is_perfect_square(number):
            n -= 1
        x += 1
    return number


print(max_num(500))
